### ISSUE TITLE
Blog example - Cannot access http://localhost:8080/web

### ISSUE THREAD

**Issue by anyachopra97** [apl-cornell/fabric#40]
In Chrome, http://localhost:8080/web says "Failed to Load: Connection refused"

**Comment by tmagrino** [comment]
AFAICT, this is due to a bug with the current implementation of the Bdb backed database.  I'm committing a change to set the blog example to use the memory backed database as a temporary workaround, while that gets sorted out.

**Comment by tmagrino** [comment]
(This is related to #36, as a note)
